#!/bin/sh

ORIG_DIR=${1:-~/gprolog-ok/examples/ExamplesFD}
THIS_DIR=${1:-~/Stage/sparse-gprolog-code/examples/ExamplesFD}
NEG_DIR=${1:-~/Stage/gprolog-code/examples/ExamplesFD}


check () {
	runs=$1
    cmd=$2
    shift
    rm -f ~/tmp/check.data
    touch ~/tmp/check.data
    d=''
    while [ $# -ge 1 ]; do
	d="$d $2"
	echo $2 >> ~/tmp/check.data
	shift
    done
    if [ "$runs" = "1" ]; then
    	printf '{\\tt %-10s %-6s                 }' "$cmd" "$d"
	else
    	printf '{\\tt %-10s %-6s $(\\times %-5s)$}' "$cmd" "$d" "$runs"
	fi
	t4=0
	t5=0
	t6=0

    for n in `seq $runs`
	do 
		cat ~/tmp/check.data | $ORIG_DIR/$cmd >~/tmp/check.1
		cat ~/tmp/check.data | $NEG_DIR/$cmd >~/tmp/check.2
		cat ~/tmp/check.data | $THIS_DIR/$cmd  >~/tmp/check.3
		fgrep -v time ~/tmp/check.1 >~/tmp/check.1a
		fgrep -v time ~/tmp/check.2 >~/tmp/check.2a
		fgrep -v time ~/tmp/check.3 >~/tmp/check.3a
		t1=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.1`
		t2=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.2`
		t3=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.3`

		t4=`expr $t4 + $t1`
		t5=`expr $t5 + $t2`
		t6=`expr $t6 + $t3`
	
		diff ~/tmp/check.1a ~/tmp/check.2a
		diff ~/tmp/check.1a ~/tmp/check.3a
	
	done
	t7=$(echo "$t4/($t5)" | bc -l)
	t8=$(echo "$t4/($t6)" | bc -l)
	printf ' & %6d & %6d & %0.2f & %6d & %0.2f \\\\\n' $t4 $t5 $t7 $t6 $t8
}


check 10 alpha
check 1000 crypta
check 100 'digit8 ff'
check 10 donald
check 100 eq20
#check 1 magic 200
check 10 multipl
check 1 partit 600
check 1 queens 29
check 1 'queens ff' 100
check 1 magsq 11
check 10 qg5 11
check 1 langford 32
check 10 interval 256

