#!/bin/sh

ORIG_DIR=${1:-~/gprolog-ok/examples/ExamplesFD}
THIS_DIR=${1:-~/Stage/sparse-gprolog-code/examples/ExamplesFD}
NEG_DIR=${1:-~/Stage/gprolog-code/examples/ExamplesFD}


check () {
    cmd=$1
    shift
    rm -f ~/tmp/check.data
    touch ~/tmp/check.data
    d=''
    while [ $# -ge 1 ]; do
	d="$d $1"
	echo $1 >> ~/tmp/check.data
	shift
    done
    printf '{\\tt %-10s %-6s}' "$cmd" "$d"
	t4=0
	t5=0
	t6=0

    for n in `seq 1000`
	do 
		cat ~/tmp/check.data | $ORIG_DIR/$cmd >~/tmp/check.1
		cat ~/tmp/check.data | $NEG_DIR/$cmd >~/tmp/check.2
		cat ~/tmp/check.data | $THIS_DIR/$cmd  >~/tmp/check.3
		fgrep -v time ~/tmp/check.1 >~/tmp/check.1a
		fgrep -v time ~/tmp/check.2 >~/tmp/check.2a
		fgrep -v time ~/tmp/check.3 >~/tmp/check.3a
		t1=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.1`
		t2=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.2`
		t3=`sed -n -e 's/time[^a-z_0-9]*\([0-9][0-9]*\)/\1/p' ~/tmp/check.3`

		t4=`expr $t4 + $t1`
		t5=`expr $t5 + $t2`
		t6=`expr $t6 + $t3`
	
		diff ~/tmp/check.1a ~/tmp/check.2a
		diff ~/tmp/check.1a ~/tmp/check.3a
	
	done
	t7=$(echo "$t5/($t4+1)" | bc -l)
	t8=$(echo "$t6/($t4+1)" | bc -l)
	printf ' & %6d & %6d & %6d & %0.2f & %0.2f \\\\\n' $t4 $t5 $t6 $t7 $t8
}


check alpha
check 'alpha ff'
#check bridge
#check cars
check crypta
check 'digit8 ff'
check donald
#check eq10
check eq20
#check five
#check gardner 5 4
check magic 100
check multipl
check partit 600
check queens 23
check queens 26
check 'queens ff' 130
#check send
#check square 3
#check square 4
#check srq
check magsq 10
check qg5 11
check langford 32
check interval 256
#check bdiag 8
#check bdonald
#check bpigeon 6 6
#check bpigeon 5 8
#check bpigeon 10 9
#check bqueens 18
#check bqueens 20
#check bramsey 13
#check bramsey 14
#check bschur 13
#check bschur 14
#check bsend


