#!/bin/sh
BENCH_PL=`cat ../PROGS`

p=`(cd ..;pwd)`
p1=`pwd`;

for i in ${*:-$BENCH_PL}
do
        echo $i
        f=$p1/$i.pl
        echo "#!/bin/sh" >$i
        echo "sed -e 's/^:- include(common)\.//' $p/$i.pl >$f" >>$i
        echo "sed -e 's/^:- include(hook)\.//' $p/common.pl >>$f" >>$i
        echo "cat $p1/HOOK.pl >>$f" >>$i
        echo "echo \"count(\${1:-1}). \" >>$f" >>$i
	echo "echo \"['$f']. \" | bp  -h 6000 -t 6000 -s 6000 2>/dev/null" >>$i
	chmod a+x $i
done
