#!/bin/sh

# compile_install SRCPATH DSTPATH

cd $1 || exit 1
(cd ../doc/; make chm)
./configure --with-msvc --with-install-dir=$2 --without-links-dir || exit 1
make || exit 1
make install

