#!/bin/sh
BENCH_PL=`cat ../PROGS`

p=`(cd ..;pwd)`
p1=`pwd`;

if test "$NATIVE" = ""; then
    mode=compactcode
else
    mode=fastcode
fi

for i in ${*:-$BENCH_PL}
do
        echo $i
        f=$i.pl
        echo "#!/bin/sh" >$i
        echo "sed -e 's/^:- include(common)\.//' $p/$i.pl >$f" >>$i
        echo "sed -e 's/^:- include(hook)\.//' $p/common.pl >>$f" >>$i
        echo "cat HOOK.pl >>$f" >>$i
	echo "echo \"prolog_flag(compiling,_,$mode), compile('$p1/$i.pl'). \" | sicstus -a \$* 2>/dev/null" >>$i
	chmod a+x $i
done
