#!/bin/sh
BENCH_PL=`cat ../PROGS`

p=`(cd ..;pwd)`
p1=`pwd`;

for i in ${*:-$BENCH_PL}
do
        echo $i
        f=$i.P
        echo "#!/bin/sh" >$i
        echo "sed -e 's/^:- include(common)\.//' $p/$i.pl >$f" >>$i
        echo "sed -e 's/^:- include(hook)\.//' $p/common.pl >>$f" >>$i
        echo "cat HOOK.pl >>$f" >>$i
	echo "echo \"asserta(count(\${1:-1})), ['$p1/$f'], q, halt. \" | xsb --noprompt --quietload --nobanner 2>/dev/null" >>$i
	chmod a+x $i
done
