/* this file is automatically generated by make_bip_list.pl */

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/all_solut.pl

bip(bagof,3).
bip(setof,3).
bip(findall,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/arith_inl.pl

bip(>=,2).
bip(<,2).
bip(>,2).
bip(=\=,2).
bip(=:=,2).
bip(is,2).
bip(=<,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/assert.pl

bip(retractall,1).
bip(assertz,1).
bip(asserta,1).
bip(retract,1).
bip(abolish,1).
bip(clause,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/atom.pl

bip(char_code,2).
bip(lower_upper,2).
bip(current_atom,1).
bip(name,2).
bip(number_codes,2).
bip(atom_codes,2).
bip(atom_length,2).
bip(atom_property,2).
bip(number_chars,2).
bip(new_atom,1).
bip(new_atom,2).
bip(new_atom,3).
bip(number_atom,2).
bip(atom_chars,2).
bip(atom_concat,3).
bip(atom_hash,2).
bip(sub_atom,5).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/call.pl

bip(context,1).
bip(:>,2).
bip(:>,1).
bip(:#,1).
bip(ccontext,1).
bip(call,2).
bip(context_valid,0).
bip(context_valid,1).
bip(:^,1).
bip(once,1).
bip(\+,1).
bip(current_unit,2).
bip(::,2).
bip(:<,2).
bip(:<,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/call_args.pl

bip(call_with_args,1).
bip(call_with_args,2).
bip(call_with_args,3).
bip(call_with_args,4).
bip(call_with_args,5).
bip(call_with_args,6).
bip(call_with_args,7).
bip(call_with_args,8).
bip(call_with_args,9).
bip(call_with_args,10).
bip(call_with_args,11).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/char_io.pl

bip(get_char,1).
bip(get_char,2).
bip(get_code,1).
bip(get_code,2).
bip(unget_byte,1).
bip(unget_byte,2).
bip(put_char,1).
bip(put_char,2).
bip(get_key,1).
bip(get_key,2).
bip(peek_code,1).
bip(peek_code,2).
bip(put_code,1).
bip(put_code,2).
bip(peek_char,1).
bip(peek_char,2).
bip(get_byte,1).
bip(get_byte,2).
bip(unget_char,1).
bip(unget_char,2).
bip(unget_code,1).
bip(unget_code,2).
bip(peek_byte,1).
bip(peek_byte,2).
bip(put_byte,1).
bip(put_byte,2).
bip(get_key_no_echo,1).
bip(get_key_no_echo,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/const_io.pl

bip(write_canonical_to_atom,2).
bip(write_term_to_chars,3).
bip(write_term_to_codes,3).
bip(write_to_atom,2).
bip(display_to_atom,2).
bip(display_to_codes,2).
bip(read_term_from_atom,3).
bip(print_to_atom,2).
bip(read_term_from_codes,3).
bip(write_term_to_atom,3).
bip(write_to_codes,2).
bip(display_to_chars,2).
bip(print_to_codes,2).
bip(read_token_from_atom,2).
bip(read_token_from_chars,2).
bip(read_from_atom,2).
bip(read_from_codes,2).
bip(read_from_chars,2).
bip(write_canonical_to_codes,2).
bip(write_to_chars,2).
bip(print_to_chars,2).
bip(read_token_from_codes,2).
bip(write_canonical_to_chars,2).
bip(writeq_to_atom,2).
bip(writeq_to_codes,2).
bip(writeq_to_chars,2).
bip(read_term_from_chars,3).
bip(format_to_atom,3).
bip(format_to_codes,3).
bip(format_to_chars,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/consult.pl

bip('.',2).
bip(consult,1).
bip(listing,0).
bip(listing,1).
bip(load,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/control.pl

bip(abort,0).
bip(repeat,0).
bip(stop,0).
bip(halt,0).
bip(halt,1).
bip(for,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/debugger.pl

bip(spypoint_condition,3).
bip(nospy,1).
bip(notrace,0).
bip(debugging,0).
bip(spy,1).
bip(leash,1).
bip(wam_debug,0).
bip(nodebug,0).
bip(trace,0).
bip(debug,0).
bip(nospyall,0).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/dec10io.pl

bip(told,0).
bip(tab,1).
bip(put,1).
bip(seeing,1).
bip(tell,1).
bip(seen,0).
bip(see,1).
bip(append,1).
bip(telling,1).
bip(skip,1).
bip(get,1).
bip(get0,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/expand.pl

bip(expand_term,2).
bip(phrase,2).
bip(phrase,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/file.pl

bip(decompose_file_name,4).
bip(absolute_file_name,2).
bip(prolog_file_name,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/flag.pl

bip(read_pl_state_file,1).
bip(argument_counter,1).
bip(write_pl_state_file,1).
bip(argument_value,2).
bip(set_prolog_flag,2).
bip(current_prolog_flag,2).
bip(argument_list,1).
bip(environ,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/format.pl

bip(format,2).
bip(format,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/g_var_inl.pl

bip(g_test_set_bit,2).
bip(g_inc,1).
bip(g_inc,2).
bip(g_inc,3).
bip(g_deco,2).
bip(g_assign,2).
bip(g_assignb,2).
bip(g_set_bit,2).
bip(g_inco,2).
bip(g_test_reset_bit,2).
bip(g_reset_bit,2).
bip(g_dec,1).
bip(g_dec,2).
bip(g_dec,3).
bip(g_array_size,2).
bip(g_read,2).
bip(g_link,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/le_interf.pl

bip(add_linedit_completion,1).
bip(find_linedit_completion,2).
bip(get_linedit_prompt,1).
bip(set_linedit_prompt,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/list.pl

bip(reverse,2).
bip(nth,3).
bip(min_list,2).
bip(permutation,2).
bip(sum_list,2).
bip(prefix,2).
bip(last,2).
bip(suffix,2).
bip(sublist,2).
bip(select,3).
bip(append,3).
bip(delete,3).
bip(memberchk,2).
bip(length,2).
bip(member,2).
bip(max_list,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/oper.pl

bip(current_op,3).
bip(op,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/os_interf.pl

bip(host_name,1).
bip(directory_files,2).
bip(exec,5).
bip(exec,4).
bip(working_directory,1).
bip(file_exists,1).
bip(temporary_file,3).
bip(architecture,1).
bip(wait,2).
bip(delete_file,1).
bip(change_directory,1).
bip(date_time,1).
bip(select,5).
bip(popen,3).
bip(make_directory,1).
bip(system,1).
bip(system,2).
bip(unlink,1).
bip(os_version,1).
bip(create_pipe,2).
bip(file_property,2).
bip(delete_directory,1).
bip(spawn,2).
bip(spawn,3).
bip(sleep,1).
bip(prolog_pid,1).
bip(temporary_name,2).
bip(shell,0).
bip(shell,1).
bip(shell,2).
bip(rename_file,2).
bip(file_permission,2).
bip(send_signal,2).
bip(fork_prolog,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/pl_error.pl

bip(current_bip_name,2).
bip(set_bip_name,2).
bip(syntax_error_info,4).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/pred.pl

bip(current_predicate,1).
bip(predicate_property,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/pretty.pl

bip(name_query_vars,2).
bip(name_singleton_vars,1).
bip(bind_variables,2).
bip(numbervars,1).
bip(numbervars,3).
bip(portray_clause,1).
bip(portray_clause,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/print.pl

bip(get_print_stream,1).
bip(print,1).
bip(print,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/random.pl

bip(get_seed,1).
bip(set_seed,1).
bip(randomize,0).
bip(random,1).
bip(random,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/read.pl

bip(char_conversion,2).
bip(read_number,1).
bip(read_number,2).
bip(read_token,1).
bip(read_token,2).
bip(read_integer,1).
bip(read_integer,2).
bip(read_term,2).
bip(read_term,3).
bip(current_char_conversion,2).
bip(read_atom,1).
bip(read_atom,2).
bip(read,1).
bip(read,2).
bip(last_read_start_line_column,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/sockets.pl

bip(socket_close,1).
bip(socket_bind,2).
bip(socket_connect,4).
bip(socket,2).
bip(socket_accept,3).
bip(socket_accept,4).
bip(hostname_address,2).
bip(socket_listen,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/sort.pl

bip(keysort,2).
bip(keysort,1).
bip(sort,2).
bip(sort,1).
bip(sort0,2).
bip(sort0,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/src_rdr.pl

bip(sr_change_options,2).
bip(sr_get_size_counters,3).
bip(sr_open,3).
bip(sr_current_descriptor,1).
bip(sr_get_include_list,2).
bip(sr_get_file_name,2).
bip(sr_write_error,2).
bip(sr_write_error,4).
bip(sr_write_error,6).
bip(sr_close,1).
bip(sr_read_term,4).
bip(sr_error_from_exception,2).
bip(sr_get_error_counters,3).
bip(sr_set_error_counters,3).
bip(sr_get_stream,2).
bip(sr_get_position,3).
bip(sr_get_include_stream_list,2).
bip(sr_new_pass,1).
bip(sr_write_message,4).
bip(sr_write_message,6).
bip(sr_write_message,8).
bip(sr_get_module,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/stat.pl

bip(system_time,1).
bip(real_time,1).
bip(statistics,0).
bip(statistics,2).
bip(cpu_time,1).
bip(user_time,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/stream.pl

bip(close,1).
bip(close,2).
bip(stream_line_column,3).
bip(stream_property,2).
bip(open_input_codes_stream,2).
bip(flush_output,0).
bip(flush_output,1).
bip(current_input,1).
bip(seek,4).
bip(set_stream_buffering,2).
bip(open_input_chars_stream,2).
bip(open_output_chars_stream,1).
bip(close_input_chars_stream,1).
bip(stream_position,2).
bip(open_output_atom_stream,1).
bip(close_input_atom_stream,1).
bip(at_end_of_stream,0).
bip(at_end_of_stream,1).
bip(character_count,2).
bip(open_input_atom_stream,2).
bip(set_stream_type,2).
bip(set_output,1).
bip(add_stream_alias,2).
bip(current_stream,1).
bip(set_stream_eof_action,2).
bip(set_input,1).
bip(current_alias,2).
bip(open_output_codes_stream,1).
bip(line_position,2).
bip(current_output,1).
bip(line_count,2).
bip(close_input_codes_stream,1).
bip(open,3).
bip(open,4).
bip(close_output_chars_stream,2).
bip(close_output_codes_stream,2).
bip(set_stream_line_column,3).
bip(set_stream_position,2).
bip(close_output_atom_stream,2).
bip(current_mirror,2).
bip(add_stream_mirror,2).
bip(remove_stream_mirror,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/term_inl.pl

bip(==,2).
bip(functor,3).
bip(@>,2).
bip(setarg,3).
bip(setarg,4).
bip(=..,2).
bip(copy_term,2).
bip(term_ref,2).
bip(compare,3).
bip(@=<,2).
bip(\==,2).
bip(@>=,2).
bip(arg,3).
bip(@<,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/top_level.pl

bip(top_level,0).
bip(break,0).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/type_inl.pl

bip(list_or_partial_list,1).
bip(atomic,1).
bip(number,1).
bip(integer,1).
bip(atom,1).
bip(partial_list,1).
bip(list,1).
bip(var,1).
bip(compound,1).
bip(callable,1).
bip(float,1).
bip(nonvar,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/unify.pl

bip(\=,2).
bip(=,2).
bip(unify_with_occurs_check,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/write.pl

bip(writeq,1).
bip(writeq,2).
bip(write_canonical,1).
bip(write_canonical,2).
bip(display,1).
bip(display,2).
bip(nl,0).
bip(nl,1).
bip(write_term,2).
bip(write_term,3).
bip(write,1).
bip(write,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_bool.pl

bip(##,2).
bip(fd_at_least_one,1).
bip(#\<=>,2).
bip(#/\,2).
bip(#\==>,2).
bip(fd_only_one,1).
bip(#<=>,2).
bip(#\,1).
bip(#==>,2).
bip(#\/\,2).
bip(fd_at_most_one,1).
bip(fd_cardinality,2).
bip(fd_cardinality,3).
bip(#\/,2).
bip(#\\/,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_infos.pl

bip(fd_vector_max,1).
bip(fd_size,2).
bip(fd_has_extra_cstr,1).
bip(fd_set_vector_max,1).
bip(fd_min,2).
bip(fd_dom,2).
bip(fd_use_vector,1).
bip(fd_max_integer,1).
bip(fd_has_vector,1).
bip(fd_max,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_math.pl

bip(#=,2).
bip(#>,2).
bip(#\=,2).
bip(#=<#,2).
bip(#>=#,2).
bip(#=<,2).
bip(#\=#,2).
bip(#>=,2).
bip(#<#,2).
bip(#=#,2).
bip(#>#,2).
bip(#<,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_optim.pl

bip(fd_minimize,2).
bip(fd_maximize,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_prime.pl

bip(fd_prime,1).
bip(fd_not_prime,1).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_symbolic.pl

bip(fd_relation,2).
bip(fd_relationc,2).
bip(fd_all_different,1).
bip(fd_exactly,3).
bip(fd_element_var,3).
bip(fd_atleast,3).
bip(fd_element,3).
bip(fd_atmost,3).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsFD/fd_values.pl

bip(fd_labelingff,1).
bip(fd_domain_bool,1).
bip(fd_domain,2).
bip(fd_domain,3).
bip(fd_labeling,1).
bip(fd_labeling,2).

% defined in /home/spa/work/maint/gprolog-cx/base/src/BipsPl/type_inl.pl

bip(fd_var,1).
bip(generic_var,1).
bip(non_generic_var,1).
bip(non_fd_var,1).
