#!/bin/sh
BENCH_PL=`cat ../PROGS`

p=`(cd ..;pwd)`
p1=`pwd`;

for i in ${*:-$BENCH_PL}
do
        echo $i
        f=$p1/$i.pl
        sed -e 's/^:- include(common)\.//' $p/$i.pl >$f
        sed -e 's/^:- include(hook)\.//' $p/common.pl >>$f
        cat $p1/HOOK.pl >>$f
        ciaoc $f
	rm -f $i.itf $i.po
done
